# Generated by Django 5.1.1 on 2024-09-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20240912_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_pics/'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_pics/'),
        ),
    ]
