# Generated by Django 5.1.1 on 2024-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_remove_dish_image_url_dish_image_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
