# Generated by Django 5.1.1 on 2024-09-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_dish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
