# Generated by Django 5.1.1 on 2024-09-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_dish_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipesteps', to='cooking.dish'),
        ),
    ]
