# Generated by Django 5.1.1 on 2024-09-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_alter_recipestep_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='rating',
        ),
    ]
