# Generated by Django 5.1.1 on 2024-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0009_remove_dish_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_numer', models.CharField(max_length=255, null=True)),
                ('subject', models.TextField()),
            ],
        ),
    ]
