# Generated by Django 5.1.1 on 2024-09-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_contact_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='message',
        ),
    ]
