# Generated by Django 5.1.1 on 2024-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0015_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
