# Generated by Django 5.1.1 on 2024-10-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0016_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
