# Generated by Django 5.1.1 on 2024-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0017_remove_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
