# Generated by Django 5.1.1 on 2024-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0018_contact_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisinecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
